# Tarea 1: Predicción de resultados del fútbol uruguayo

Este notebook tiene el objetivo de reflejar todos los pasos que se consideraron necesarios para satisfacer los requerimientos de la Tarea 1 del laboratorio de Apendizajes Automáticos.

Para la correcta verificación de cada uno de los pasos indicados en el notebook, se asume de antemano que se cuenta con la instalación de Python 3.12.x en su máquina local.

In [3]:
# Instalación de las librerías Python necesarias

%pip install pandas numpy matplotlib scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (3.0.5)
Requirement already satisfied: numpy in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (2.5.2)
Requirement already satisfied: matplotlib in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (3.11.1)
Requirement already satisfied: scikit-learn in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (1.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (2.25.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\users\lucas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: C:\Users\lucas\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
import numpy as np
import sklearn

--- 
### 1. Carga del Dataset y Descripción de Atributos

In [5]:
DATASET_FILE = "./futbol_uruguayo.csv" 

dataset = pd.read_csv(DATASET_FILE)

print(f"Cantidad total de instancias: ", dataset.shape[0])
print(f"Cantidad total de atributos: ", dataset.shape[1])
dataset.head()

Cantidad total de instancias:  15207
Cantidad total de atributos:  17

,home,away,date,gh,ga,full_time,competition,home_ident,away_ident,home_country,away_country,home_code,away_code,home_continent,away_continent,continent,level
0,Bella Vista,Defensor Sporting,1932-03-05,1.0,2.0,F,uruguay,Bella Vista (Uruguay),Defensor Sporting (Uruguay),uruguay,uruguay,UY,UY,South America,South America,South America,national
1,CA Penarol,River Plate,1932-03-05,1.0,1.0,F,uruguay,CA Penarol (Uruguay),River Plate (Uruguay),uruguay,uruguay,UY,UY,South America,South America,South America,national
2,Montevideo Wanderers,Racing Club,1932-03-05,3.0,0.0,F,uruguay,Montevideo Wanderers (Uruguay),Racing Club (Uruguay),uruguay,uruguay,UY,UY,South America,South America,South America,national
3,Central Espanol,Rampla Juniors Futbol Club,1932-03-05,1.0,0.0,F,uruguay,Central Espanol (Uruguay),Rampla Juniors Futbol Club (Uruguay),uruguay,uruguay,UY,UY,South America,South America,South America,national
4,Nacional,Institucion Atletica Sud America,1932-03-05,2.0,0.0,F,uruguay,Nacional (Uruguay),Institucion Atletica Sud America (Uruguay),uruguay,uruguay,UY,UY,South America,South America,South America,national

#### Descripción de los atributos:

| Atributo | Descripción |
| :--- | :--- |
| **`home`** | Nombre del equipo local (no necesariamente único) |
| **`away`** | Nombre del equipo visitante (no necesariamente único) |
| **`date`** | Fecha del partido |
| **`gh`** | Goles del equipo local (incluyendo tiempo extra y penales) |
| **`ga`** | Goles del equipo visitante (incluyendo tiempo extra y penales) |
| **`full_time`** | "F"=el partido terminó en 90', "E"=tiempo extra, "P"=penales |
| **`competition`** | Nombre del país de la liga o nombre de la competición int. |
| **`home_ident`** | Identificador único del equipo local |
| **`away_ident`** | Identificador único del equipo visitante |
| **`home_country`** | País del equipo local |
| **`away_country`** | País del equipo visitante |
| **`home_code`** | Código de país del equipo local |
| **`away_code`** | Código de país del equipo visitante |
| **`home_continent`** | Continente del equipo local |
| **`away_continent`** | Continente del equipo visitante |
| **`continent`** | Continente de la competición |
| **`level`** | "national"= liga local, "international"= copa internacional |

--- 
### 2. Definición de la Variable Objetivo (`ganador`)

El objetivo del modelo es predecir el resultado final de un partido de fútbol, clasificándolo en una de tres categorías posibles: victoria local, victoria visitante o empate.

Dado que el dataset original no incluye directamente una columna de resultado, se deduce la variable objetivo **`ganador`** mediante la comparación de los goles anotados por el equipo local (`gh`) y el visitante (`ga`):

* Si $\text{gh} > \text{ga} \implies$ **`L`**
* Si $\text{ga} > \text{gh} \implies$ **`V`**
* Si $\text{gh} == \text{ga} \implies$ **`E`**

In [6]:
dataset["ganador"] = np.select(
    [
        dataset["gh"] > dataset["ga"],     
        dataset["gh"] < dataset["ga"],
        dataset["gh"] == dataset["ga"],
    ],
    [
        "L",
        "V",
        "E",
    ],
    default="sin_dato",
)

dataset.head()

,home,away,date,gh,ga,full_time,competition,home_ident,away_ident,home_country,away_country,home_code,away_code,home_continent,away_continent,continent,level,ganador
0,Bella Vista,Defensor Sporting,1932-03-05,1.0,2.0,F,uruguay,Bella Vista (Uruguay),Defensor Sporting (Uruguay),uruguay,uruguay,UY,UY,South America,South America,South America,national,V
1,CA Penarol,River Plate,1932-03-05,1.0,1.0,F,uruguay,CA Penarol (Uruguay),River Plate (Uruguay),uruguay,uruguay,UY,UY,South America,South America,South America,national,E
2,Montevideo Wanderers,Racing Club,1932-03-05,3.0,0.0,F,uruguay,Montevideo Wanderers (Uruguay),Racing Club (Uruguay),uruguay,uruguay,UY,UY,South America,South America,South America,national,L
3,Central Espanol,Rampla Juniors Futbol Club,1932-03-05,1.0,0.0,F,uruguay,Central Espanol (Uruguay),Rampla Juniors Futbol Club (Uruguay),uruguay,uruguay,UY,UY,South America,South America,South America,national,L
4,Nacional,Institucion Atletica Sud America,1932-03-05,2.0,0.0,F,uruguay,Nacional (Uruguay),Institucion Atletica Sud America (Uruguay),uruguay,uruguay,UY,UY,South America,South America,South America,national,L

Concretado este paso, se observa que la información que proveen los atributos "gh" y "ga" ya se ve contemplada por la variable objetivo. Por lo tanto, su presencia en el dataset no agrega significancia al entrenamiento del modelo y se deben remover las columnas correspondientes a dichos atributos.

--- 
### 3. Selección de Atributos

En esta etapa del preprocesamiento se realiza una selección de los atributos del dataset con el objetivo de maximizar la capacidad de aprendizaje del modelo en la clasificación de las instancias. Para ello, se examina cada atributo de forma individual para evaluar si contribuye de manera significativa al entrenamiento o si, dadas sus características, puede ser removido sin perjudicar el desempeño del modelo.

Se evalúan las siguientes condiciones de los atributos:

* **Atributos constantes:** No contribuyen al aprendizaje del modelo debido a que mantienen el mismo valor para todas las instancias del dataset (varianza cero).
* **Atributos redundantes:** Representan valores equivalentes dentro del dataset, por lo que basta con conservar uno de ellos.

#### A. Detección de Atributos Constantes

A modo informativo, se evalúan los atributos constantes en el dataset contando la cantidad de instancias con valores diferentes para cada atributo en el dataset. Luego, se imprime el nombre de aquellos atributos para los que existe un único valor equivalente para todas las instancias en el dataset.

In [7]:
# Detección de Atributos Constantes
constantes = dataset.nunique(dropna=False)[dataset.nunique(dropna=False) == 1]
print("Atributos constantes detectados:")
print(constantes)

# Eliminar todas las columnas con un solo valor único
dataset = dataset.loc[:, dataset.nunique() > 1]

Atributos constantes detectados:
competition       1
home_country      1
away_country      1
home_code         1
away_code         1
home_continent    1
away_continent    1
continent         1
level             1
dtype: int64

Los atributos constantes son los siguientes:
* `competition`, `home_country`, `away_country` (Todos refieren a Uruguay).
* `home_code`, `away_code` (Código constante `UY`).
* `home_continent`, `away_continent`, `continent` (Todos refieren a `South America`).
* `level` (Constante con el valor `national`).

Estos atributos se excluyen para que no formen parte del entrenamiento del modelo.

#### B. Detección de Atributos Redundantes

In [25]:
# Verificar cuántos identificadores tiene cada nombre de equipo, y viceversa
home_name_to_id = dataset.groupby("home")["home_ident"].nunique(dropna=False)
home_id_to_name = dataset.groupby("home_ident")["home"].nunique(dropna=False)

away_name_to_id = dataset.groupby("away")["away_ident"].nunique(dropna=False)
away_id_to_name = dataset.groupby("away_ident")["away"].nunique(dropna=False)

print(f"Cada valor de home se corresponde a un solo valor de home_ident, y viceversa: ", (home_name_to_id == 1).all()  & (home_id_to_name == 1).all())
print(f"Cada valor de away se corresponde a un solo valor de away_ident, y viceversa: ", (away_name_to_id == 1).all()  & (away_id_to_name == 1).all())

dataset = dataset.drop(columns=['home_ident', 'away_ident'])

Cada valor de home se corresponde a un solo valor de home_ident, y viceversa:  True
Cada valor de away se corresponde a un solo valor de away_ident, y viceversa:  True

Existe una correspondencia 1:1, mantener ambas variables introduciría información redundante. Elegimos quedarnos con `home` y `away` y se descartan sus identificadores (`home_ident` y `away_ident`).

**Obervación**: La aplicación de este método "a mano" para identificar a los atributos redundantes es más que suficiente para el dataset con el que estamos trabajando, sin embargo, si se tratara de un dataset con una cantidad más grande de atributos entonces sería necesario automatizar de alguna forma la identificación de los atributos redundantes mediante la medición de la correlación de atributos.

#### C. Descomposición del atributo `date`

El atributo `date` se divide en los atributos `day`, `month` y `year` para representar sus componentes por separado. Esta transformación facilita que el modelo identifique patrones relacionados con el momento del año en que se disputó el partido, como diferencias entre meses, temporadas o períodos históricos. Además, evita tratar cada fecha completa como un valor independiente, lo que podría dificultar el aprendizaje. Una vez extraídos estos componentes, se elimina el atributo `date` original para evitar mantener información redundante.

In [15]:
dataset["date"] = pd.to_datetime(dataset["date"])
dataset["day_of_week"] = dataset["date"].dt.day_name()
dataset["month"] = dataset["date"].dt.month
dataset['year'] = dataset['date'].dt.year

---
### 4. Análisis de Balance y Estratificación:

In [16]:
# Cálculo de la dispersión de instancias respecto a las clases
porcentajes = dataset["ganador"].value_counts(normalize=True).mul(100).round(2)

instancias_L = float(porcentajes.iloc[0])
instancias_V = float(porcentajes.iloc[1])
instancias_E = float(porcentajes.iloc[2])

print(f"Porcentaje de instancias correspondientes a la clase L: ", instancias_L)
print(f"Porcentaje de instancias correspondientes a la clase V: ", instancias_V)
print(f"Porcentaje de instancias correspondientes a la clase E: ", instancias_E)

Porcentaje de instancias correspondientes a la clase L:  44.35
Porcentaje de instancias correspondientes a la clase V:  28.2
Porcentaje de instancias correspondientes a la clase E:  27.44

La distribución de la clase objetivo muestra las siguientes proporciones:
* **`L`**: **44.35%**
* **`V`**: **28.20%**
* **`E`**: **27.44%**

---
### 5. División del Conjunto de Datos

Se debe dividir el conjunto dataset de la siguiente forma:

Conjunto de entrenamiento los partidos jugados hasta el año 2023 inclusive y como conjunto de evaluación los partidos jugados en 2024 y 2025.

In [30]:
dataset = dataset.sort_values(by='date').reset_index(drop=True)

# Instancias con partidos jugados hasta el año 2023 inclusive
df_entrenamiento = dataset[dataset['year'] <= 2023]
X_train = df_entrenamiento.drop(columns=['date','ganador', 'gh', 'ga', 'year']) # ACLARAR LA ELIMINACION DE YEAR
Y_train = df_entrenamiento['ganador']

df_evaluacion = dataset[dataset['year'] > 2023]
X_test = df_evaluacion.drop(columns=['date', 'ganador', 'gh', 'ga', 'year'])
Y_test = df_evaluacion['ganador']

print(f"Dimensiones de X_train (Entrenamiento): {X_train.shape}")
print(f"Dimensiones de X_test (Evaluación):    {X_test.shape}")

Dimensiones de X_train (Entrenamiento): (14734, 5)
Dimensiones de X_test (Evaluación):    (473, 5)

In [34]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.compose import ColumnTransformer


numeric_features = ['month']
categorical_features = ['home', 'away', 'full_time', 'day_of_week']

numeric_pipeline = Pipeline([
    ('imputer', SimpleImputer())
])

categorical_pipeline = Pipeline([
    ('imputer', SimpleImputer(fill_value='missing', strategy='constant')),
    ('onehot', OneHotEncoder(
        handle_unknown='ignore',
        sparse_output=False
    ))],
)

preprocessing = ColumnTransformer(
    transformers=[
        ('numeric', numeric_pipeline, numeric_features),
        ('categorical', categorical_pipeline, categorical_features),
    ],
)


pipeline = Pipeline([
    ('preprocessing', preprocessing),
    ('model', DecisionTreeClassifier(random_state=62))
])

X_train.head()

,home,away,full_time,day_of_week,month
0,Bella Vista,Defensor Sporting,F,Saturday,3
1,CA Penarol,River Plate,F,Saturday,3
2,Montevideo Wanderers,Racing Club,F,Saturday,3
3,Central Espanol,Rampla Juniors Futbol Club,F,Saturday,3
4,Nacional,Institucion Atletica Sud America,F,Saturday,3

In [35]:
param_grid = {
    # Preprocesamiento numérico
    'preprocessing__numeric__imputer__strategy': [
        'mean',
        'median'
    ],
    # Árbol de decisión
    'model__max_depth': [
        3,
        6,
        10,
        15,
        None
    ],
    'model__criterion':[
        'gini','entropy'
    ],
    # Minima ganancia permitida para un atributo
    'model__min_impurity_decrease': [
        0.0,
        0.001,
        0.005,
        0.01,
        0.05
    ]
}

In [36]:
from sklearn.model_selection import GridSearchCV, TimeSeriesSplit

cv_temporal = TimeSeriesSplit(n_splits=10)

grid_search = GridSearchCV(
    estimator=pipeline,
    param_grid=param_grid,
    scoring='accuracy',
    cv=cv_temporal,
    n_jobs=-1,
    refit=True
)

# GridSearchCV realiza internamente la validación cruzada
grid_search.fit(X_train, Y_train)

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=10, test_size=None),
             estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(transformers=[('numeric',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer())]),
                                                                         ['month']),
                                                                        ('categorical',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(fill_value='missing',
                                                                                                        strategy='constant')),
                                                                                         ('onehot',
                                                                                          OneHotEncode...
                                                                                                        sparse_output=False))]),
                                                                         ['home',
                                                                          'away',
                                                                          'full_time',
                                                                          'day_of_week'])])),
                                       ('model',
                                        DecisionTreeClassifier(random_state=62))]),
             n_jobs=-1,
             param_grid={'model__criterion': ['gini', 'entropy'],
                         'model__max_depth': [3, 6, 10, 15, None],
                         'model__min_impurity_decrease': [0.0, 0.001, 0.005,
                                                          0.01, 0.05],
                         'preprocessing__numeric__imputer__strategy': ['mean',
                                                                       'median']},
             scoring='accuracy')

In [38]:
import pandas as pd

resultados_gs = pd.json_normalize(grid_search.best_params_)
resultados_gs.columns = [col.replace('preprocessing__', '').replace('model__', '') for col in resultados_gs.columns]
resultados_gs['accuracy_cv'] = grid_search.best_score_

test_accuracy = grid_search.score(X_test, Y_test)

resultados_gs['accuracy_test'] = test_accuracy

display(resultados_gs)

,criterion,max_depth,min_impurity_decrease,numeric__imputer__strategy,accuracy_cv,accuracy_test
0,entropy,10,0.001,mean,0.480807,0.479915